@baseUrl = http://localhost:3002
@contentType = application/json

### Root
GET {{baseUrl}}/

### Health check
GET {{baseUrl}}/api/health

### User registration
POST {{baseUrl}}/api/auth/register
Content-Type: {{contentType}}

{
  "fullName": "Arif Yahya",
  "email": "arifyahyaa@gmail.com",
  "password": "password"
}

### User login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "password"
}

### Set Auth Token
@token = {{login.response.body.data.token}}

### Get user profile
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Logout user
POST {{baseUrl}}/api/auth/logout
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Get all users (admin only)
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Get user by ID (admin only)
GET {{baseUrl}}/api/users/1
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Create new user (admin only)
POST {{baseUrl}}/api/users
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "fullName": "New User",
  "email": "newuser2@example.com",
  "password": "password",
  "role": "admin"
}

### Update user (admin only)
PATCH {{baseUrl}}/api/users/2
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "fullName": "Updated User",
  "email": "updateduser@example.com"
}

### Delete user (admin only)
DELETE {{baseUrl}}/api/users/2
Authorization: Bearer {{token}}

### Event creation
POST {{baseUrl}}/api/admin/events
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "title": "Tech Conference 2026 version 2",
  "description": "A conference about the latest in tech.",
  "capacity": 300,
  "startAt": "2026-09-15 15:00",
  "endAt": "2026-09-15 18:00",
  "location": "New York City"
}

### Get all events
GET {{baseUrl}}/api/admin/events
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Get event by ID
GET {{baseUrl}}/api/admin/events/1
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Update event
PATCH {{baseUrl}}/api/admin/events/1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "title": "Updated Tech Conference 2026",
  "description": "An updated description for the tech conference.",
  "capacity": 350,
  "startAt": "2026-09-15 16:00",
  "endAt": "2026-09-15 19:00",
  "location": "San Francisco"
}

### Delete event
DELETE {{baseUrl}}/api/admin/events/1
Authorization: Bearer {{token}}

### Publish event
POST {{baseUrl}}/api/admin/events/1/publish
Authorization: Bearer {{token}}

### Cancel event
POST {{baseUrl}}/api/admin/events/1/cancel
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "reason": "Due to unforeseen circumstances, we have to cancel the event."
}

### Move event to draft
POST {{baseUrl}}/api/admin/events/1/move-to-draft
Authorization: Bearer {{token}}

### Archive event
POST {{baseUrl}}/api/admin/events/1/archive
Authorization: Bearer {{token}}

### Get public events
GET {{baseUrl}}/api/events?sortBy=price&sort=asc

### Get public events detail
GET {{baseUrl}}/api/events/7

### Create Order
POST {{baseUrl}}/api/orders
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "eventId": 7,
  "quantity": 6,
  "paymentMethod": "BCA_VA"
}

### Order Detail
GET {{baseUrl}}/api/orders/9c23301d-2606-4a52-91cf-6771693e3f08
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

### Ticket Check-in
POST {{baseUrl}}/api/admin/check-ins
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "qrToken": "271d80340acf628cb30cdb8fe64f3277"
}

