@baseUrl = http://localhost:3002
@contentType = application/json

### Root
GET {{baseUrl}}/

### Health check
GET {{baseUrl}}/api/health

### User registration
POST {{baseUrl}}/api/auth/register
Content-Type: {{contentType}}

{
  "fullName": "Arif Yahya",
  "email": "arifyahyaa@gmail.com",
  "password": "password"
}

### User login
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "password"
}

### Set Auth Token
@token = {{login.response.body.data.token}}

### Get user profile
GET {{baseUrl}}/api/auth/me
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Logout user
POST {{baseUrl}}/api/auth/logout
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Get all users (admin only)
GET {{baseUrl}}/api/users
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Get user by ID (admin only)
GET {{baseUrl}}/api/users/1
Authorization: Bearer {{token}}
Accept: {{contentType}}

### Create new user (admin only)
POST {{baseUrl}}/api/users
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "fullName": "New User",
  "email": "newuser1@example.com",
  "password": "password",
  "role": "admin"
}
